name: CI

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  install:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v4
    - name: Cache bun
      uses: actions/cache@v3
      with:
        path: ~/.bun
        key: bun-${{ matrix.node-version }}-${{ hashFiles('**/bun.lockb') }}
        restore-keys: |
          ${{ runner.os }}-bun-
    - uses: oven-sh/setup-bun@v2
    - run: bun install
