name: CI

on:
  - push
  - pull_request

jobs:
  install:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    steps:
    - uses: actions/checkout@v4
    - uses: oven-sh/setup-bun@v2
    - run: echo "cache-key=node-${{ matrix.node-version }}"
    - run: bun install

  test:
    runs-on: ubuntu-latest
    needs: install
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    steps:
    - uses: actions/checkout@v4
    - run: bun run test

  lint:
    runs-on: ubuntu-latest
    needs: install
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    steps:
    - uses: actions/checkout@v4
    - run: bun run xo

  build:
    runs-on: ubuntu-latest
    needs: install
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    steps:
    - uses: actions/checkout@v4
    - run: bun run build
