name: CI

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v4
      with:
        path: ~/.bun
        key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
        restore-keys: ${{ runner.os }}-bun-
    - uses: oven-sh/setup-bun@v2
    - run: bun install
    - run: bun run test

  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache/restore@v4
      with:
        path: ~/.bun
        key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
    - run: ln -s ~/.bun/bin/bun /usr/local/bin/bun
    - run: bun run test
