name: CI

on:
  workflow_dispatch:
  push:
    branches:
    - main
  pull_request:

jobs:
  build:
    uses: ./.github/actions/setup
    steps:
    - run: bun run build

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: oven-sh/setup-bun@v2
    - run: bun install
    - run: bun run test
    
