name: CI

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  setup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v4
      with:
        path: ~/.bun
        key: bun-${{ matrix.node-version }}-${{ hashFiles('**/bun.lockb') }}
        restore-keys: |
          ${{ runner.os }}-bun-
    - uses: oven-sh/setup-bun@v2
    - run: bun install

  test:
    runs-on: ubuntu-latest
    needs: setup
    strategy:
      matrix:
        node-version: [20.x]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v4
      with:
        path: ~/.bun
        key: bun-${{ matrix.node-version }}-${{ hashFiles('**/bun.lockb') }}
    - run: bun run test
