name: CI

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        task: [build, test]
    steps:
    - uses: actions/checkout@v4
    - uses: oven-sh/setup-bun@v2
    - run: bun install
    - run: bun run ${{ matrix.task }}
