name: CI

on:
  workflow_dispatch:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    uses: ./.github/workflows/script-runner.yml
    with:
      script_name: "build"

  test:
    uses: ./.github/workflows/script-runner.yml
    with:
      script_name: "test"

  lint:
    uses: ./.github/workflows/script-runner.yml
    with:
      script_name: "ci"
