name: Run script

on:
  workflow_call:
    inputs:
      script_name:
        required: true
        type: string

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: oven-sh/setup-bun@v2
    - run: bun install
    - run: npm run ${{ inputs.script_name }}
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
