name: Setup workflow

on:
  workflow_call:
    inputs:
      task:
        required: true
        type: string

jobs:
  run-task:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: oven-sh/setup-bun@v2
    - run: bun install
